### PR TITLE
Add method PublishWithRoutingKey

### PR DESCRIPTION
**Pull request by aalexanderkevin**

### CODE REVIEW

**Review by sihendra — CHANGES_REQUESTED** [review]
@aalexanderkevin Since this library main feature is the abstraction, I think better to add variadic function paramater for this purpose, so we can still use specific implementation functionality while still using the abstraction function. WDYT?

Example:
```
func (m *RabbitMqClient) Publish(topicName string, body []byte, options ...Option) error {
...
}
```

**Review by sihendra — CHANGES_REQUESTED** [review]
@aalexanderkevin I think the option should be typed for clarity,

```go
// msgbus.go

type PublishOption struct {
     RoutingKey string
} 

func WithRoutingKey(routingKey string) func(*PublishOption) {
    return func(p *PublishOption) {
        p.RoutingKey = routingKey 
     }
}

```

```go
// rabbitmq.go

func (m* RabbitMqClient) Publish(topicName string, msg []byte, options ...func(*PublishOption)) *Server {
  opt := &PublishOption{}
  for _, o := range options {
    o(opt)
  }
  
  ...
  use the opt
}

```

**Review by sihendra — CHANGES_REQUESTED** [review]
@aalexanderkevin please create separate test case for the publish with routing key option

**Comment by aalexanderkevin** [comment]
move to this https://github.com/sihendra/go-msgbuzz/pull/6
change the PR destination to branch develop

**Pull request closed without merging**
